project_name: port-forwarder
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

before:
  hooks:
    - go mod vendor

builds:
  - id: binary
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
    main: ./main.go